feat(1): add home screen
WiseVladlen/Books pull request #1
Opened 2023-10-16 13:21 UTC by WiseVladlen

2023-10-16 17:37 UTC, KolasikOmetov requested changes

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/data/repository/book_repository.dart
> +        BookModel(
Есть лаконичнее конструкция:
List.generate

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/domain/model/book_model.dart
> +  const BookModel({
Структура класса
Внутри класса следует использовать следующий порядок метод и полей:

конструкторы класса

static const поля

static поля

final поля
приватные поля (get/set)
публичные поля (get/set)
@override
публичные методы (static также здесь)

@protected методы
приватные методы

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/bloc/home_bloc.dart
> +    add(LoadBooksEvent());
Лучше вызывать в ui во время создания блока при открытии страницы. Тут тоже норм, но мотивировано это тем, что этот эвент вызывается тогда, когда отрывается страница (привязка события к конкретному сценарию).

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/bloc/home_bloc.dart
> +    emit(state.copyWith(books: bookRepository.getBooks()));
а у тебя getBooks будет синхронным? сомневаюсь. +надо продумать что показывать во время загрузки и ошибки получения данных.

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/bloc/home_event.dart
> +  List<Object> get props => [];
бесполезно extends Equatable. sealed уже даёт правильное сравнение по конструктору объекта. Тем более сравнение идёт по значениям переданным в props (которых там вообще нет...).
да и за чем тут sealed?

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/bloc/home_event.dart
> +final class LoadBooksEvent extends HomeEvent {}
const конструктор добавь

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/bloc/home_state.dart
> +  final List<BookModel>? books;
Порядок надо поменять. Конструктор всегда первый.

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/book_tile.dart
> +    required this.imageLink,
лучше сразу избавляться от нулов сделав дефолтным `imageLink = ''`. Внутри уже не придётся проверять на нулл, а только imageLink.isEmpty

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/book_tile.dart
> +  factory BookTile.fromModel(BookModel model) {
все конструкторы сверху

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/book_tile.dart
> +      padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
Рили?) Это же Padding

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/book_tile.dart
> +            decoration: BoxDecoration(
Почему не нравится контейнер:
Внутри много лишних проверок, которые срабатывают при ребилде. Посмотри исходники.
Можно заменить на SizedBox DecoratedBox

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/book_tile.dart
> +                  )
Можно вынести в отдельный общий виджет и файл, чтобы не завязываться на библиотеке CachedNetworkImage на весь проект. Так же уже будет готовая конфигурация и перекопировать её в будущем не придётся.

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/book_tile.dart
> +          const SizedBox(width: 16),
Лучше Padding.
https://docs.google.com/document/d/1FMpKSkfM3R4lnD47ePSZXFZkLXKpd0o74hy-rCCCxxM/edit?usp=sharing

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/book_tile.dart
> +                  style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
Бери из темы.

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/book_tile.dart
> +  }
1 - последний метод всегда build.
2 - https://youtu.be/IOyq-eTRhvo

2023-10-16 17:37 UTC, KolasikOmetov commented on lib/presentation/home/home_page.dart
> +          title: const Center(child: Text('Books')),
Локализация?

2023-10-16 17:37 UTC, KolasikOmetov commented on pubspec.yaml
> +  cached_network_image: ^3.3.0
лучше убрать ^
https://t.me/surf_flutter/228

2023-10-16 17:37 UTC, KolasikOmetov commented on pubspec.yaml
>    flutter:
и на 22 строке зафиксируй версию флаттера.
flutter: 3.13.6

2023-10-16 18:22 UTC, WiseVladlen commented on lib/presentation/home/bloc/home_event.dart
> +  List<Object> get props => [];
Использовал это для сравнения события + видел в других репозиториях. Мне либо использовать sealed, либо extends Equatable или вообще их оба убирать?

2023-10-19 05:18 UTC, KolasikOmetov requested changes

2023-10-19 05:18 UTC, KolasikOmetov commented on lib/presentation/home/bloc/home_state.dart
> +enum BookDownloadStatus {
Может энам общим сделать? Чтобы это не только для книг. И в домейн часть вынести его

2023-10-19 05:28 UTC, KolasikOmetov commented on lib/presentation/home/bloc/home_bloc.dart
> +      emit(state.copyWith(bookDownloadStatus: BookDownloadStatus.inProgress));
это не нужно в трае

2023-10-19 05:28 UTC, KolasikOmetov commented on lib/presentation/home/bloc/home_bloc.dart
> +    } on Exception catch (error, stack) {
Прям любая? Тогда её надо тоже дальше передавать по коду: в catch rethrow делать. Возможно много каких ошибок и их нужно логировать уметь.

2023-10-19 05:28 UTC, KolasikOmetov commented on lib/presentation/home/book_tile.dart
> +    required this.imageLink,
Не исправил.

2023-10-19 05:28 UTC, KolasikOmetov commented on lib/utils/utils.dart
> +const String placeholderPath = 'assets/book-cover-placeholder.jpg';
Есть генераторы для ресурсов, посмотри в пабе пакеты.

2023-10-19 05:28 UTC, KolasikOmetov commented on pubspec.yaml
>    flutter:
не сделал

2023-10-19 05:36 UTC, WiseVladlen commented on lib/presentation/home/bloc/home_bloc.dart
> +    } on Exception catch (error, stack) {
Ты предлагаешь перед этим добавить, например, on DioException?

2023-10-19 05:44 UTC, WiseVladlen commented on pubspec.yaml
>    flutter:
Я смотрел на пабе и ее устанавливали для enviroment, впрочем, как я и сделал на 23-ей строке. Нужно так, как ниже?

dependencies:
flutter:
version: 3.13.6

2023-10-19 17:04 UTC, KolasikOmetov commented on lib/presentation/home/bloc/home_bloc.dart
> +      emit(state.copyWith(bookDownloadStatus: DownloadStatus.failure));
Ну ну, а как же принцип dry?

2023-10-19 17:42 UTC, KolasikOmetov approved these changes

2023-10-19 17:43 UTC, merged